In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
data=pd.read_csv("sentiment_5_class.csv")
data

Phrase  Sentiment
0      injects just enough freshness into the proceed...          3
1                                                   that          2
2      never plays as dramatic even when dramatic thi...          0
3      None of this is very original , and it is n't ...          0
4      , Madonna gives her best performance since Abe...          3
...                                                  ...        ...
18384  to balance pointed , often incisive satire and...          3
18385  have to be a most hard-hearted person not to b...          4
18386                could young romantics out on a date          3
18387                                 could be this good          3
18388                                    such a dungpile          0

[18389 rows x 2 columns]

In [39]:
test_data=pd.read_csv("sentiment_5_class_test.csv")
test_data

Phrase  Sentiment
0     makes for a touching love story , mainly becau...          3
1                                 a truly magical movie          4
2                                                 check          3
3        is a remarkably accessible and haunting film .          4
4                                          are too cute          3
...                                                 ...        ...
3673                                     feel realistic          3
3674                                    startling story          3
3675                                             hollow          1
3676                              released the outtakes          2
3677  What a bewilderingly brilliant and entertainin...          4

[3678 rows x 2 columns]

In [40]:
train_data=pd.read_csv("sentiment_5_class_train.csv")
train_data

Phrase  Sentiment
0                                           the prisoner          2
1      The sheer joy and pride they took in their wor...          3
2      has never made a more sheerly beautiful film t...          3
3      the story has the sizzle of old news that has ...          3
4                                           far superior          4
...                                                  ...        ...
14706                                    really cool bit          3
14707                                   Next Great Thing          3
14708          shockingly bad and absolutely unnecessary          0
14709  First , for a movie that tries to be smart , i...          1
14710  it 's difficult not to cuss him out severely f...          1

[14711 rows x 2 columns]

## Data analysis and visualization

In [41]:
total_df=len(data)
total_df

18389

In [42]:
data.head()

Phrase  Sentiment
0  injects just enough freshness into the proceed...          3
1                                               that          2
2  never plays as dramatic even when dramatic thi...          0
3  None of this is very original , and it is n't ...          0
4  , Madonna gives her best performance since Abe...          3

In [43]:
sentiment_list=data.Sentiment.unique().tolist()
print(sentiment_list)

[3, 2, 0, 4, 1]


In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18389 entries, 0 to 18388
Data columns (total 2 columns):
Phrase       18389 non-null object
Sentiment    18389 non-null int64
dtypes: int64(1), object(1)
memory usage: 287.5+ KB


In [45]:
data.describe()

Sentiment
count  18389.000000
mean       2.760672
std        1.113323
min        0.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        4.000000

In [46]:
# data.hist()
# plt.show()

## Feature extraction and preprocessing

In [47]:
x_train=train_data.Phrase.tolist()
x_test=test_data.Phrase.tolist()
# print(x_test)
y_train=train_data.Sentiment.tolist()
y_test=test_data.Sentiment.tolist()

## CountVectorizer
CountVectorizer

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
c_vectorizer = CountVectorizer()

In [50]:
c_vectorizer.fit(x_train)
c_vectorizer.get_feature_names()

['10',
 '100',
 '10th',
 '12',
 '120',
 '129',
 '13',
 '15',
 '168',
 '1790',
 '1899',
 '19',
 '1915',
 '1920',
 '1940s',
 '1950s',
 '1953',
 '1957',
 '1970s',
 '1971',
 '1975',
 '1980s',
 '1984',
 '1989',
 '1990',
 '19th',
 '20',
 '2000',
 '2002',
 '20th',
 '21st',
 '25',
 '26',
 '270',
 '30',
 '300',
 '3000',
 '3d',
 '48',
 '4ever',
 '50',
 '50s',
 '60',
 '60s',
 '70s',
 '71',
 '78',
 '80',
 '84',
 '86',
 '88',
 '90',
 '95',
 'abandon',
 'abandoned',
 'abel',
 'abhorrent',
 'ability',
 'able',
 'aborted',
 'abound',
 'about',
 'above',
 'abridged',
 'absolute',
 'absolutely',
 'absorb',
 'absorbed',
 'absorbing',
 'absorption',
 'abstract',
 'absurdist',
 'absurdly',
 'abundant',
 'abuse',
 'abyss',
 'academic',
 'academy',
 'accent',
 'accents',
 'accept',
 'acceptable',
 'accepting',
 'accepts',
 'access',
 'accessibility',
 'accessible',
 'accident',
 'accompanies',
 'accomplish',
 'accomplished',
 'accomplishes',
 'accomplishments',
 'account',
 'accountant',
 'accumulated',
 'ac

In [51]:
c_train_v=c_vectorizer.transform(x_train)

c_train_v.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [52]:

c_test_v=c_vectorizer.transform(x_test)
c_test_v.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# TfidfVectorizer

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [54]:
t_vectorizer=TfidfVectorizer()
t_vectorizer.fit(x_train) 
t_vectorizer.get_feature_names()

['10',
 '100',
 '10th',
 '12',
 '120',
 '129',
 '13',
 '15',
 '168',
 '1790',
 '1899',
 '19',
 '1915',
 '1920',
 '1940s',
 '1950s',
 '1953',
 '1957',
 '1970s',
 '1971',
 '1975',
 '1980s',
 '1984',
 '1989',
 '1990',
 '19th',
 '20',
 '2000',
 '2002',
 '20th',
 '21st',
 '25',
 '26',
 '270',
 '30',
 '300',
 '3000',
 '3d',
 '48',
 '4ever',
 '50',
 '50s',
 '60',
 '60s',
 '70s',
 '71',
 '78',
 '80',
 '84',
 '86',
 '88',
 '90',
 '95',
 'abandon',
 'abandoned',
 'abel',
 'abhorrent',
 'ability',
 'able',
 'aborted',
 'abound',
 'about',
 'above',
 'abridged',
 'absolute',
 'absolutely',
 'absorb',
 'absorbed',
 'absorbing',
 'absorption',
 'abstract',
 'absurdist',
 'absurdly',
 'abundant',
 'abuse',
 'abyss',
 'academic',
 'academy',
 'accent',
 'accents',
 'accept',
 'acceptable',
 'accepting',
 'accepts',
 'access',
 'accessibility',
 'accessible',
 'accident',
 'accompanies',
 'accomplish',
 'accomplished',
 'accomplishes',
 'accomplishments',
 'account',
 'accountant',
 'accumulated',
 'ac

In [55]:

t_train_v=t_vectorizer.transform(x_train)
t_train_v.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [56]:
t_test_v=t_vectorizer.transform(x_test)
t_test_v.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
from sklearn.svm import SVC

In [58]:
model=SVC(random_state=1)
model.fit(c_train_v,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

## Model Evalution in CountVectorizer


In [59]:
from sklearn import metrics

In [60]:
y_pred = model.predict(c_test_v)

In [61]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.45      0.57       247
           1       0.62      0.30      0.40       291
           2       0.78      0.20      0.32       469
           3       0.60      0.91      0.73      1759
           4       0.76      0.52      0.62       912

    accuracy                           0.64      3678
   macro avg       0.71      0.48      0.53      3678
weighted avg       0.68      0.64      0.61      3678



## Model evalution in TfidfVectorizer 



In [62]:

y_pred = model.predict(t_test_v)

In [63]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.01      0.02       247
           1       0.50      0.01      0.03       291
           2       0.57      0.16      0.24       469
           3       0.50      0.99      0.66      1759
           4       0.84      0.04      0.09       912

    accuracy                           0.51      3678
   macro avg       0.68      0.24      0.21      3678
weighted avg       0.63      0.51      0.37      3678



## Grid Search

In [64]:
from sklearn.model_selection import GridSearchCV

In [65]:

grid_param = {'kernel':('linear', 'rbf'), 'C':(1, 10)}

In [66]:
from sklearn.metrics import make_scorer, f1_score

### find best_score and params for CountVectorizer 

In [67]:

scorer = make_scorer(f1_score, average='micro')
clf = GridSearchCV(SVC(), grid_param,scoring=scorer)
clf.fit(c_train_v, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': (1, 10), 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=make_scorer(f1_score, average=micro), verbose=0)

In [68]:
print(clf.best_score_, clf.best_params_)

0.6987284810677747 {'C': 10, 'kernel': 'rbf'}


### find best_score and params for TfidfVectorizer 

In [69]:
scorer = make_scorer(f1_score, average='micro')
clf = GridSearchCV(SVC(), grid_param,scoring=scorer)
clf.fit(t_train_v, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': (1, 10), 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=make_scorer(f1_score, average=micro), verbose=0)

In [70]:
print(clf.best_score_, clf.best_params_)

0.6977766782555387 {'C': 10, 'kernel': 'rbf'}


## Final Model
CountVectorizer

In [71]:
model = SVC(random_state=1,kernel='rbf', C=10.0)
model.fit(c_train_v, y_train)
y_pred = model.predict(c_test_v)
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.66      0.70       247
           1       0.63      0.56      0.59       291
           2       0.70      0.72      0.71       469
           3       0.74      0.80      0.77      1759
           4       0.71      0.64      0.67       912

    accuracy                           0.72      3678
   macro avg       0.71      0.68      0.69      3678
weighted avg       0.72      0.72      0.72      3678



## Final Model
TfidfVectorizer 

In [72]:
model = SVC(random_state=1,kernel='rbf', C=10.0)
model.fit(t_train_v, y_train)
y_pred = model.predict(c_test_v)
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.08      0.13       247
           1       0.47      0.06      0.10       291
           2       0.73      0.32      0.45       469
           3       0.51      0.95      0.66      1759
           4       0.54      0.07      0.12       912

    accuracy                           0.52      3678
   macro avg       0.55      0.30      0.29      3678
weighted avg       0.54      0.52      0.42      3678

